### PR TITLE
Unused generic

### PR DESCRIPTION
**Pull request by vorner**
Some little cleanups.

### CODE REVIEW

**Comment by fralalonde** [comment]
Nice.

**Comment by vorner** [comment]
Hmm. Did the thing return as part of some merging conflict, or something? It seems this is still present in the recently-released 0.7.2 ☹.

https://docs.rs/dipstick/0.7.2/dipstick/struct.AtomicBucket.html#method.unset_stats

**Comment by fralalonde** [comment]
Ah, that's weird. I'll nuke it (again) and release 0.7.3. Do you have a tool to find these? I'm not running clippy as part of the pre-release make script, maybe I should...

**Comment by fralalonde** [comment]
All right, I fixed it + a bunch of clippy warnings (some fixed, some made quiet). 
Made 0.7.3 release.
Now running clippy as part of `make` checks.

**Comment by vorner** [comment]
I don't have a tool, I just tried to use it once again when upgrading and it still didn't work.

Thanks for the very fast response.

**Pull request merged**
