### PR TITLE
Feature/observers

### PR DESCRIPTION
**Pull request by fralalonde**

### CODE REVIEW

**Comment by fralalonde** [comment]
- Still missing `self.notify_flush_listeners()` for most output's `flush()`
- `on_flush` requires metrics to be `mut` 
- the behavior for adding multiple flush listeners on sibling outputs needs to be sorted out

**Comment by fralalonde** [comment]
I'm not sure about the `Observer` struct being worth much... It could be easily replaced by a `Gauge`-updating  closure wherever it is used, either `on_flush` or `every`  scheduled.

**Comment by fralalonde** [comment]
@mixalturek last call for API changes, this is ready to merge! 

I'm satisfied with the new API and I believe I went back to something close to your original proposal:
```
    let uptime = metrics.gauge("uptime");
    metrics.observe(uptime, || 6).on_flush();

    metrics
        .observe(metrics.gauge("threads"), thread_count)
        .every(Duration::from_secs(1));
```
What do you think?

I'm sorry for taking so long and clobbering your original PR... Some lower-level changes were required for this to work, mainly the flush notifications and a new shared-thread scheduler (so we don't create a new thread for very observed gauge). 

Your original commits are still in the commit log for posterity, if it's something you care about :)

**Comment by mixalturek** [comment]
Hi, I'm sorry, I had and have too many other tasks from many directions and didn't have time for this at all. I also received no email notification about your work until yesterday, so I fully missed everything. The API described in the comment above looks great!

**Pull request merged**
