### PR TITLE
Stream::to_file: Open for writing

### PR DESCRIPTION
**Pull request by vorner**
And create if necessary.

### CODE REVIEW

**Comment by vorner** [comment]
Hmm, I wonder if even this is the correct way. Should it overwrite the file when it exists, or should it append?

**Comment by fralalonde** [comment]
Make it selectable? You might want to append to a single file or create a new one if the date is in the filename (for example). Trying to create a new file (`to_new_file`) if it already exists would result in an error.

**Comment by fralalonde** [comment]
And give `to_new_file` an `overwrite` parameter.

**Comment by vorner** [comment]
So the current one should append? Currently, it overwrites existing files.

**Comment by fralalonde** [comment]
Yeah. Appending is the safest default - no data loss, always works (should create if not exists). `to_new_file` is a longer name and takes an extra parameter, implying more dragons.

**Pull request merged**
